name: DeepEval Automated Tests

on:
  push:
    branches:
      - main
      - feature/fpaa-agent-engine
  pull_request:
    branches:
      - main
      - feature/fpaa-agent-engine

jobs:
  run-evaluations:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v4

      - name: ☁️ Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 🚀 Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: 🐍 Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 📦 Install Dependencies
        run: uv sync

      - name: 🧪 Run DeepEval
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_CLOUD_PROJECT: "strong-kit-475107-k1"
        run: uv run deepeval test run tests/